name: gene-copy-number
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - pysam
  - gffutils
  - openjdk>=17
  - samtools
  - pip
  - pip:
      - .